// <auto-generated />
using System;
using System.Collections.Generic;
using CareLanka.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CareLanka.Api.Data.Migrations
{
    [DbContext(typeof(CareLankaDbContext))]
    [Migration("20260910082607_Patient_AddCancelNote")]
    partial class Patient_AddCancelNote
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CareLanka.Api.Data.Entities.Common.PatientAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_patient_accounts");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_patient_accounts_phone")
                        .HasFilter("is_active");

                    b.ToTable("patient_accounts", (string)null);
                });

            modelBuilder.Entity("CareLanka.Api.Data.Entities.Common.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("PatientAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_account_id");

                    b.Property<string>("PrincipalType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("principal_type");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("revoked_reason");

                    b.Property<Guid?>("StaffMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("staff_member_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("PatientAccountId")
                        .HasDatabaseName("ix_refresh_tokens_patient_account_id");

                    b.HasIndex("StaffMemberId")
                        .HasDatabaseName("ix_refresh_tokens_staff_member_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_refresh_tokens_hash");

                    b.HasIndex("PrincipalType", "StaffMemberId", "PatientAccountId")
                        .HasDatabaseName("ix_refresh_tokens_principal");

                    b.ToTable("refresh_tokens", null, t =>
                        {
                            t.HasCheckConstraint("ck_refresh_tokens_one_principal", "(principal_type = 'staff' AND staff_member_id IS NOT NULL AND patient_account_id IS NULL) OR (principal_type = 'patient' AND patient_account_id IS NOT NULL AND staff_member_id IS NULL)");

                            t.HasCheckConstraint("ck_refresh_tokens_principal_type", "principal_type IN ('staff', 'patient')");
                        });
                });

            modelBuilder.Entity("CareLanka.Api.Data.Entities.Common.StaffMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("department");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_staff_members");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_staff_members_email")
                        .HasFilter("is_active");

                    b.ToTable("staff_members", null, t =>
                        {
                            t.HasCheckConstraint("ck_staff_members_role", "role IN ('ward_nurse', 'doctor', 'ambulance_crew', 'general_staff', 'duty_manager', 'hospital_administrator', 'equipment_manager')");
                        });
                });

            modelBuilder.Entity("CareLanka.Api.Data.Entities.Patient.Admission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AdmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("admitted_at");

                    b.Property<string>("CancelNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cancel_note");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("cancel_reason");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CategorySetAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("category_set_at");

                    b.Property<Guid>("CategorySetByStaffMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_set_by_staff_member_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("DetailsComplete")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("boolean")
                        .HasColumnName("details_complete")
                        .HasComputedColumnSql("cardinality(missing_fields) = 0", true);

                    b.Property<DateTimeOffset?>("DetailsCompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("details_completed_at");

                    b.Property<DateTimeOffset?>("DischargedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("discharged_at");

                    b.Property<string>("DispatchId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("dispatch_id");

                    b.Property<DateTimeOffset?>("ExpectedArrivalAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expected_arrival_at");

                    b.Property<bool>("IsInfectious")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_infectious");

                    b.Property<List<string>>("MissingFields")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("missing_fields")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<Guid?>("ReportedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reported_by_user_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Urgency")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("urgency");

                    b.HasKey("Id")
                        .HasName("pk_admissions");

                    b.HasIndex("CategorySetByStaffMemberId")
                        .HasDatabaseName("ix_admissions_category_set_by_staff_member_id");

                    b.HasIndex("DispatchId")
                        .HasDatabaseName("ix_admissions_dispatch_id")
                        .HasFilter("dispatch_id IS NOT NULL");

                    b.HasIndex("ReportedByUserId")
                        .HasDatabaseName("ix_admissions_reported_by_user_id");

                    b.HasIndex("Status", "ExpectedArrivalAt")
                        .HasDatabaseName("ix_admissions_status_expected_arrival_at");

                    b.HasIndex(new[] { "PatientId" }, "ix_admissions_patient_id")
                        .HasDatabaseName("ix_admissions_patient_id");

                    b.HasIndex(new[] { "PatientId" }, "ux_admissions_open_patient")
                        .IsUnique()
                        .HasDatabaseName("ux_admissions_open_patient")
                        .HasFilter("status NOT IN ('discharged', 'cancelled')");

                    b.ToTable("admissions", null, t =>
                        {
                            t.HasCheckConstraint("ck_admissions_cancel_reason", "cancel_reason IS NULL OR cancel_reason IN ('diverted_to_other_hospital', 'false_alarm', 'died_en_route', 'patient_refused', 'no_show')");

                            t.HasCheckConstraint("ck_admissions_category", "category IN ('icu', 'hdu', 'inpatient', 'day_case', 'outpatient')");

                            t.HasCheckConstraint("ck_admissions_source", "source IN ('emergency', 'walk_in', 'pre_registered')");

                            t.HasCheckConstraint("ck_admissions_status", "status IN ('awaiting_bed', 'awaiting_approval', 'bed_reserved', 'admitted', 'ready_for_discharge', 'discharged', 'cancelled')");

                            t.HasCheckConstraint("ck_admissions_urgency", "urgency IN ('routine', 'urgent', 'emergency')");
                        });
                });

            modelBuilder.Entity("CareLanka.Api.Data.Entities.Patient.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AdmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("admission_id");

                    b.Property<Guid?>("BookedByStaffMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("booked_by_staff_member_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_appointments");

                    b.HasIndex("AdmissionId")
                        .HasDatabaseName("ix_appointments_admission_id");

                    b.HasIndex("BookedByStaffMemberId")
                        .HasDatabaseName("ix_appointments_booked_by_staff_member_id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_appointments_patient_id");

                    b.HasIndex("ScheduledAt", "Status")
                        .HasDatabaseName("ix_appointments_scheduled_at_status");

                    b.ToTable("appointments", null, t =>
                        {
                            t.HasCheckConstraint("ck_appointments_status", "status IN ('scheduled', 'checked_in', 'completed', 'cancelled', 'no_show')");
                        });
                });

            modelBuilder.Entity("CareLanka.Api.Data.Entities.Patient.BedAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AdmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("admission_id");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedByStaffMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_staff_member_id");

                    b.Property<string>("AssignedBy")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("assigned_by");

                    b.Property<Guid>("BedId")
                        .HasColumnType("uuid")
                        .HasColumnName("bed_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDowngrade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_downgrade");

                    b.Property<string>("OverrideReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("override_reason");

                    b.Property<string>("ReleaseReason")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("release_reason");

                    b.Property<DateTimeOffset?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at");

                    b.Property<DateTimeOffset?>("ReservedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reserved_until");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id")
                        .HasName("pk_bed_assignments");

                    b.HasIndex("AdmissionId")
                        .IsUnique()
                        .HasDatabaseName("ux_bed_assignments_live_admission")
                        .HasFilter("status IN ('reserved', 'occupied')");

                    b.HasIndex("ApprovedByStaffMemberId")
                        .HasDatabaseName("ix_bed_assignments_approved_by_staff_member_id");

                    b.HasIndex("BedId")
                        .IsUnique()
                        .HasDatabaseName("ux_bed_assignments_live_bed")
                        .HasFilter("status IN ('reserved', 'occupied')");

                    b.HasIndex("ReservedUntil")
                        .HasDatabaseName("ix_bed_assignments_reserved_until")
                        .HasFilter("status = 'reserved'");

                    b.ToTable("bed_assignments", null, t =>
                        {
                            t.HasCheckConstraint("ck_bed_assignments_assigned_by", "assigned_by IN ('agent', 'user')");

                            t.HasCheckConstraint("ck_bed_assignments_release_reason", "release_reason IS NULL OR release_reason IN ('discharged', 'hold_expired', 'cancelled', 'transferred', 'rejected')");

                            t.HasCheckConstraint("ck_bed_assignments_status", "status IN ('reserved', 'occupied', 'released')");
                        });
                });

            modelBuilder.Entity("CareLanka.Api.Data.Entities.Patient.Discharge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AdmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("admission_id");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<Guid?>("ConfirmedByStaffMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("confirmed_by_staff_member_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("FlaggedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("flagged_at");

                    b.Property<string>("FlaggedBy")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("flagged_by");

                    b.Property<string>("SummaryNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("summary_note");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_discharges");

                    b.HasIndex("AdmissionId")
                        .IsUnique()
                        .HasDatabaseName("ux_discharges_admission_id");

                    b.HasIndex("ConfirmedByStaffMemberId")
                        .HasDatabaseName("ix_discharges_confirmed_by_staff_member_id");

                    b.ToTable("discharges", null, t =>
                        {
                            t.HasCheckConstraint("ck_discharges_flagged_by", "flagged_by IN ('agent', 'user')");
                        });
                });

            modelBuilder.Entity("CareLanka.Api.Data.Entities.Patient.DischargeChecklistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DischargeId")
                        .HasColumnType("uuid")
                        .HasColumnName("discharge_id");

                    b.Property<bool>("IsMandatory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_mandatory");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("item_type");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<DateTimeOffset?>("TickedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ticked_at");

                    b.Property<Guid?>("TickedByStaffMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticked_by_staff_member_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_discharge_checklist_items");

                    b.HasIndex("TickedByStaffMemberId")
                        .HasDatabaseName("ix_discharge_checklist_items_ticked_by_staff_member_id");

                    b.HasIndex("DischargeId", "ItemType")
                        .IsUnique()
                        .HasDatabaseName("ux_discharge_checklist_items_discharge_item_type");

                    b.ToTable("discharge_checklist_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_discharge_checklist_items_item_type", "item_type IN ('clinical_clearance', 'medication_issued', 'billing_settled', 'follow_up_recorded', 'transport_arranged')");
                        });
                });

            modelBuilder.Entity("CareLanka.Api.Data.Entities.Patient.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("address");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("EmergencyContactName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("emergency_contact_name");

                    b.Property<string>("EmergencyContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("emergency_contact_phone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("gender");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Nic")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nic");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("TempReference")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("temp_reference");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_account_id");

                    b.HasKey("Id")
                        .HasName("pk_patients");

                    b.HasIndex("Nic")
                        .IsUnique()
                        .HasDatabaseName("ux_patients_nic")
                        .HasFilter("nic IS NOT NULL AND is_active");

                    b.HasIndex("TempReference")
                        .IsUnique()
                        .HasDatabaseName("ux_patients_temp_reference")
                        .HasFilter("temp_reference IS NOT NULL AND is_active");

                    b.HasIndex("UserAccountId")
                        .IsUnique()
                        .HasDatabaseName("ux_patients_user_account_id")
                        .HasFilter("user_account_id IS NOT NULL AND is_active");

                    b.ToTable("patients", null, t =>
                        {
                            t.HasCheckConstraint("ck_patients_gender", "gender IN ('male', 'female', 'other', 'unknown')");

                            t.HasCheckConstraint("ck_patients_identifier", "nic IS NOT NULL OR phone IS NOT NULL OR temp_reference IS NOT NULL");
                        });
                });

            modelBuilder.Entity("CareLanka.Api.Data.Entities.Patient.Ward", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("GenderPolicy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("gender_policy");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WardType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ward_type");

                    b.HasKey("Id")
                        .HasName("pk_wards");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_wards_name")
                        .HasFilter("is_active");

                    b.ToTable("wards", null, t =>
                        {
                            t.HasCheckConstraint("ck_wards_gender_policy", "gender_policy IN ('male', 'female', 'mixed')");

                            t.HasCheckConstraint("ck_wards_type", "ward_type IN ('icu', 'hdu', 'general', 'maternity', 'pediatric', 'isolation')");
                        });
                });

            modelBuilder.Entity("CareLanka.Api.Data.Entities.Common.RefreshToken", b =>
                {
                    b.HasOne("CareLanka.Api.Data.Entities.Common.PatientAccount", "PatientAccount")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("PatientAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_refresh_tokens_patient_accounts_patient_account_id");

                    b.HasOne("CareLanka.Api.Data.Entities.Common.StaffMember", "StaffMember")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("StaffMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_refresh_tokens_staff_members_staff_member_id");

                    b.Navigation("PatientAccount");

                    b.Navigation("StaffMember");
                });

            modelBuilder.Entity("CareLanka.Api.Data.Entities.Patient.Admission", b =>
                {
                    b.HasOne("CareLanka.Api.Data.Entities.Common.StaffMember", null)
                        .WithMany()
                        .HasForeignKey("CategorySetByStaffMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_admissions_staff_members_category_set_by_staff_member_id");

                    b.HasOne("CareLanka.Api.Data.Entities.Patient.Patient", "Patient")
                        .WithMany("Admissions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_admissions_patients_patient_id");

                    b.HasOne("CareLanka.Api.Data.Entities.Common.PatientAccount", null)
                        .WithMany()
                        .HasForeignKey("ReportedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_admissions_patient_accounts_reported_by_user_id");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("CareLanka.Api.Data.Entities.Patient.Appointment", b =>
                {
                    b.HasOne("CareLanka.Api.Data.Entities.Patient.Admission", "Admission")
                        .WithMany()
                        .HasForeignKey("AdmissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_appointments_admissions_admission_id");

                    b.HasOne("CareLanka.Api.Data.Entities.Common.StaffMember", null)
                        .WithMany()
                        .HasForeignKey("BookedByStaffMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_appointments_staff_members_booked_by_staff_member_id");

                    b.HasOne("CareLanka.Api.Data.Entities.Patient.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_appointments_patients_patient_id");

                    b.Navigation("Admission");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("CareLanka.Api.Data.Entities.Patient.BedAssignment", b =>
                {
                    b.HasOne("CareLanka.Api.Data.Entities.Patient.Admission", "Admission")
                        .WithMany("BedAssignments")
                        .HasForeignKey("AdmissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bed_assignments_admissions_admission_id");

                    b.HasOne("CareLanka.Api.Data.Entities.Common.StaffMember", null)
                        .WithMany()
                        .HasForeignKey("ApprovedByStaffMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_bed_assignments_staff_members_approved_by_staff_member_id");

                    b.Navigation("Admission");
                });

            modelBuilder.Entity("CareLanka.Api.Data.Entities.Patient.Discharge", b =>
                {
                    b.HasOne("CareLanka.Api.Data.Entities.Patient.Admission", "Admission")
                        .WithOne("Discharge")
                        .HasForeignKey("CareLanka.Api.Data.Entities.Patient.Discharge", "AdmissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_discharges_admissions_admission_id");

                    b.HasOne("CareLanka.Api.Data.Entities.Common.StaffMember", null)
                        .WithMany()
                        .HasForeignKey("ConfirmedByStaffMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_discharges_staff_members_confirmed_by_staff_member_id");

                    b.Navigation("Admission");
                });

            modelBuilder.Entity("CareLanka.Api.Data.Entities.Patient.DischargeChecklistItem", b =>
                {
                    b.HasOne("CareLanka.Api.Data.Entities.Patient.Discharge", "Discharge")
                        .WithMany("ChecklistItems")
                        .HasForeignKey("DischargeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_discharge_checklist_items_discharges_discharge_id");

                    b.HasOne("CareLanka.Api.Data.Entities.Common.StaffMember", null)
                        .WithMany()
                        .HasForeignKey("TickedByStaffMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_discharge_checklist_items_staff_members_ticked_by_staff_mem");

                    b.Navigation("Discharge");
                });

            modelBuilder.Entity("CareLanka.Api.Data.Entities.Patient.Patient", b =>
                {
                    b.HasOne("CareLanka.Api.Data.Entities.Common.PatientAccount", null)
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_patients_patient_accounts_user_account_id");
                });

            modelBuilder.Entity("CareLanka.Api.Data.Entities.Common.PatientAccount", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("CareLanka.Api.Data.Entities.Common.StaffMember", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("CareLanka.Api.Data.Entities.Patient.Admission", b =>
                {
                    b.Navigation("BedAssignments");

                    b.Navigation("Discharge");
                });

            modelBuilder.Entity("CareLanka.Api.Data.Entities.Patient.Discharge", b =>
                {
                    b.Navigation("ChecklistItems");
                });

            modelBuilder.Entity("CareLanka.Api.Data.Entities.Patient.Patient", b =>
                {
                    b.Navigation("Admissions");

                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
