// <auto-generated />
using System;
using CareLanka.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CareLanka.Api.Data.Migrations
{
    [DbContext(typeof(CareLankaDbContext))]
    partial class CareLankaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CareLanka.Api.Data.Entities.Common.PatientAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_patient_accounts");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_patient_accounts_phone")
                        .HasFilter("is_active");

                    b.ToTable("patient_accounts", (string)null);
                });

            modelBuilder.Entity("CareLanka.Api.Data.Entities.Common.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("PatientAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_account_id");

                    b.Property<string>("PrincipalType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("principal_type");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("revoked_reason");

                    b.Property<Guid?>("StaffMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("staff_member_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("PatientAccountId")
                        .HasDatabaseName("ix_refresh_tokens_patient_account_id");

                    b.HasIndex("StaffMemberId")
                        .HasDatabaseName("ix_refresh_tokens_staff_member_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_refresh_tokens_hash");

                    b.HasIndex("PrincipalType", "StaffMemberId", "PatientAccountId")
                        .HasDatabaseName("ix_refresh_tokens_principal");

                    b.ToTable("refresh_tokens", null, t =>
                        {
                            t.HasCheckConstraint("ck_refresh_tokens_one_principal", "(principal_type = 'staff' AND staff_member_id IS NOT NULL AND patient_account_id IS NULL) OR (principal_type = 'patient' AND patient_account_id IS NOT NULL AND staff_member_id IS NULL)");

                            t.HasCheckConstraint("ck_refresh_tokens_principal_type", "principal_type IN ('staff', 'patient')");
                        });
                });

            modelBuilder.Entity("CareLanka.Api.Data.Entities.Common.StaffMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("department");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_staff_members");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_staff_members_email")
                        .HasFilter("is_active");

                    b.ToTable("staff_members", null, t =>
                        {
                            t.HasCheckConstraint("ck_staff_members_role", "role IN ('ward_nurse', 'doctor', 'ambulance_crew', 'general_staff', 'duty_manager', 'hospital_administrator', 'equipment_manager')");
                        });
                });

            modelBuilder.Entity("CareLanka.Api.Data.Entities.Common.RefreshToken", b =>
                {
                    b.HasOne("CareLanka.Api.Data.Entities.Common.PatientAccount", "PatientAccount")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("PatientAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_refresh_tokens_patient_accounts_patient_account_id");

                    b.HasOne("CareLanka.Api.Data.Entities.Common.StaffMember", "StaffMember")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("StaffMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_refresh_tokens_staff_members_staff_member_id");

                    b.Navigation("PatientAccount");

                    b.Navigation("StaffMember");
                });

            modelBuilder.Entity("CareLanka.Api.Data.Entities.Common.PatientAccount", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("CareLanka.Api.Data.Entities.Common.StaffMember", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
