SELECT 'CREATE ROLE carelanka_app LOGIN'
WHERE NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'carelanka_app') \gexec

ALTER ROLE carelanka_app WITH LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE PASSWORD :'app_password';

GRANT USAGE ON SCHEMA public TO carelanka_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO carelanka_app;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO carelanka_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO carelanka_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO carelanka_app;
